# Generated by Django 3.0.5 on 2021-06-24 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='choice_vote',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.Choice'),
        ),
    ]
