# Generated by Django 3.0.5 on 2021-06-24 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_voter_choice_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='choice_vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Choice'),
        ),
    ]
