# Generated by Django 3.0.5 on 2021-06-24 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210624_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='choice_vote',
        ),
        migrations.AddField(
            model_name='voter',
            name='question_vote',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.Question'),
        ),
    ]
