# Generated by Django 3.0.5 on 2021-06-24 21:41

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210624_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='json',
            field=jsonfield.fields.JSONField(default=0),
        ),
    ]
