# Generated by Django 3.0.5 on 2021-06-24 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_voter_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='is_vote',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='question_vote',
        ),
    ]
