# Generated by Django 3.0.5 on 2021-06-25 12:22

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210624_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='json',
            field=jsonfield.fields.JSONField(default={0, '0'}),
        ),
    ]
