# Generated by Django 3.0.5 on 2021-06-25 12:23

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210625_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='json',
            field=jsonfield.fields.JSONField(default={'0'}),
        ),
    ]
